apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: stockmaster
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: stockmaster
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS stockmaster_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS stockmaster_product CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS stockmaster_stock CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS stockmaster_order CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: stockmaster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: stockmaster
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.26
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init
          configMap:
            name: mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: stockmaster
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

