apiVersion: v1
kind: Secret
metadata:
  name: stockmaster-secret
  namespace: stockmaster
type: Opaque
stringData:
  MYSQL_PASSWORD: root
  JWT_SECRET: stockmaster-k8s-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stockmaster-config
  namespace: stockmaster
data:
  EUREKA_URL: http://eureka-service:8761/eureka/
  CONFIG_URL: http://config-service:8888
  MYSQL_USER: root
  USER_DB_URL: jdbc:mysql://mysql:3306/stockmaster_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  PRODUCT_DB_URL: jdbc:mysql://mysql:3306/stockmaster_product?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  STOCK_DB_URL: jdbc:mysql://mysql:3306/stockmaster_stock?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  ORDER_DB_URL: jdbc:mysql://mysql:3306/stockmaster_order?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai

