name: Deploy To Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy StockMaster
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/mysql/mysql.yaml
          kubectl apply -f k8s/services/base-config.yaml
          kubectl apply -f k8s/services/apps.yaml
          kubectl -n stockmaster rollout status deployment/eureka-service
          kubectl -n stockmaster rollout status deployment/config-service
          kubectl -n stockmaster rollout status deployment/gateway-service
          kubectl -n stockmaster rollout status deployment/frontend-nginx

